- name: Deploy Application
  hosts: all
  become: yes

  tasks:
    - name: Copy App Files
      copy:
        src: /home/worker2/ansible_ci_cd/app.py   # Update this path
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'
